import { ListDetailView } from '~/components/Layouts'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({ children }) {
  return <ListDetailView list={null} hasDetail={false} detail={children} />
}
