import author from "./author";
import blockContent from "./blockContent";
import caseStudy from "./caseStudy";
import coverImage from "./coverImage";
import media from "./media";
import post from "./post";
import siteConfig from "./siteConfig";
import social from "./social";
import tag from "./tag";
export const schemaTypes = [media, social, coverImage, author, post, blockContent, tag, siteConfig, caseStudy];
